config/routes.rb
Dialeto::Application.routes.draw do
  match 'categorias/auto_complete' => 'categorias#auto_complete'
  match 'perfis/auto_complete' => 'perfis#auto_complete'
  match 'categorias/:id_categoria/propagandas' => 'propagandas#propagandas_da_categoria'
  match 'categorias/:id_categoria/videos' => 'videos#videos_da_categoria'
  match 'videos/validate_video' => 'videos#validate_video'
  
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  
  resources :token_authentications, :only => [:create, :destroy]
  resources :user, :controller => "user"
  resources :users
  resources :contatos
  resources :videos
  resources :propagandas
  resources :categorias
  resources :perfis

  root :to => "perfis#index"
end

app/models/propaganda.rb
# encoding: utf-8
class Propaganda < ActiveRecord::Base
  attr_reader :categoria_tokens
  attr_accessible :categoria_tokens, :nome, :image, :media
  
  scope :with_out_categoria, where("#{quoted_table_name}.id NOT IN (SELECT `categorias_propagandas`.propaganda_id FROM `categorias_propagandas`)")
    
  has_attached_file :image,
    :storage => :s3,
    :s3_credentials => "#{Rails.root.to_s}/config/s3.yml",
    :path => "/:style/:id/:filename",
    :bucket => 'dialeto_propaganda'
    
  has_attached_file :media,
      :storage => :s3,
      :s3_credentials => "#{Rails.root.to_s}/config/s3.yml",
      :path => "/:style/:id/:filename",
      :bucket => 'dialeto_propaganda'
  
  validates_presence_of :nome
  validates_uniqueness_of :nome, :case_sensitive => false
  validates_attachment_presence :image
  validates_attachment_presence :media
  validates_attachment_content_type :media, 
                                    :content_type => ["image/jpeg", "image/png", "image/gif"], 
                                    :message => "Formato de arquivo não suportado."
  validates_attachment_content_type :image, 
                                    :content_type => ["image/jpeg", "image/png", "image/gif"], 
                                    :message => "Formato de arquivo não suportado."

  has_and_belongs_to_many :categorias
    
  def image_url
    image.url
  end
  
  def media_url
    media.url
  end
  
  def as_json(options)
    super({:except => [:image_updated_at, :media_updated_at], :methods => [:image_url, :media_url] })
  end
  
  def categoria_tokens=(ids)
    self.categoria_ids = ids.split(",")
  end
end

app/controllers/propagandas_controller.rb
class PropagandasController < ApplicationController
  before_filter :authenticate_user!  
  load_and_authorize_resource
  
  def index
    if can? :manage, Propaganda
      @propagandas = Propaganda.all
    else
      @propagandas = Propaganda.with_out_categoria
    end
  
    respond_to do |format|
      format.html
      format.json { render :json => @propagandas }
    end
  end
  
  def propagandas_da_categoria
    if can? :manage, Propaganda
      categoria = Categoria.find(params[:id_categoria])        
    else
      categoria = Categoria.categorias_do_usuario(current_user).where(:id => params[:id_categoria]).first
    end
    raise ActiveRecord::RecordNotFound.new if categoria.nil?
    
    @propagandas = categoria.propagandas
    
    respond_to do |format|
      format.html { render :template => "propagandas/index.html.erb" }
      format.json { render :json => @propagandas }
    end
  end

  def show
    @propaganda = Propaganda.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @propaganda }
    end
  end

  def new
    @propaganda = Propaganda.new
  end

  def edit
    @propaganda = Propaganda.find(params[:id])
  end

  def create
    @propaganda = Propaganda.new(params[:propaganda])
        
    if @propaganda.save
      redirect_to(@propaganda, :notice => 'Propaganda criada com sucesso.')
    else
      render :action => "new"
    end
  end

  def update
    @propaganda = Propaganda.find(params[:id])
        
    params[:propaganda].delete(:media) if params[:propaganda][:media].blank?
    params[:propaganda].delete(:image) if params[:propaganda][:image].blank?

    if @propaganda.update_attributes(params[:propaganda])
      redirect_to(@propaganda, :notice => 'Propaganda atualizada com sucesso.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @propaganda = Propaganda.find(params[:id])
    @propaganda.destroy
    redirect_to(propagandas_url)
  end
end

app/helpers/propagandas_helper.rb
module PropagandasHelper
end

app/views/propagandas/_form.html.erb
<% if @propaganda.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@propaganda.errors.count, "erro") %> proibiram a propaganda de ser salva.</h2>
    <ul>
	    <% @propaganda.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
    </ul>
  </div>
<% end %>

<%= simple_form_for(@propaganda, :html => {:multipart => true, :id => "insert-form"}) do |f| %>
	<div class="form-left">
		<%= f.label :nome, "Nome" %>
	</div>
	<div class="form-right">
		<%= f.text_field :nome %>
	</div>
	<div class="form-left">
		<%= f.label :categoria_tokens, "Categorias" %>
	</div>
	<div class="form-right">
		<%= f.text_field :categoria_tokens, "data-pre" => @propaganda.categorias.map(&:attributes).to_json %>
	</div>
	<% if @propaganda.new_record? %>
		<div class="form-left">
			<%= f.label :media, "Media" %>
		</div>
		<div class="form-right">
			<%= f.file_field :media %>
			<span class="inline-help">O formato aceito é o .mov com codec H.264.</span>
		</div>
	<% end %>
	<% if @propaganda.new_record? %>
		<div class="form-left">
			<%= f.label :image, "Imagem" %>
		</div>
		<div class="form-right">
				<%= f.file_field :image, :class => "txt", :id => "preview" %>
	      <span class="inline-help">A imagem precisa ter 448x250 pixels.</span>
	   </div>
	<% end %>
  <div class="clear" style="text-align:right; width:372px; padding-top: 30px;">
		<%= f.submit :submit %>
	</div>
<% end %>
<%= content_for :js do %>
$("#propaganda_categoria_tokens").tokenInput("/categorias/auto_complete.json", {
	crossDomain: false,
	prePopulate: $(this).data("pre"),
  theme: "facebook"
});
$("#propaganda_nome").focus();
<% end %>

app/views/propagandas/edit.html.erb
<h1>Editing propaganda</h1>

<%= render 'form' %>

<%= link_to 'Show', @propaganda %> |
<%= link_to 'Back', propagandas_path %>

app/views/propagandas/index.html.erb
<h2 class="top-title">Propagandas</h2>
<div class="Propagandas">
	<div style="margin:10px 0px 20px 10px">
		<%= link_to 'Inserir Nova Propaganda', new_propaganda_path, :id => "add-propaganda", :class => "submit button large ui-corner-all" %>
  </div>
	<table class="list-table">
		<thead class="ui-widget-header ui-corner-all">
			<tr>
				<th width="100%">Nome</th>
				<th colspan="4">Ações</th>
			</tr>
		</thead>
		<tbody>    	
			<% @propagandas.each do |propaganda| %>
				<tr>
					<td><%= propaganda.nome %></td>
					<td><%= link_to "Visualizar", propaganda, :class => "view-record" %></td>
					<% if can? :manage, @propagandas %>
						<td><%= link_to "Editar", edit_propaganda_path(propaganda), :class => "edit-record" %></td>
						<td><%= link_to "Deletar", propaganda, :method => :delete, :confirm => "Você tem certeza?", :class => "delete-record" %></td>
					<% end %>
			  </tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/propagandas/new.html.erb
<h1>New propaganda</h1>

<%= render 'form' %>

<%= link_to 'Back', propagandas_path, :class => "new" %>

app/views/propagandas/show.html.erb
<p>
  <b>Nome:</b>
  <%= @propaganda.nome %>
</p>

<p>
	<%= image_tag @propaganda.image.url %>
</p>

<% if can? :manage, @propaganda %>
	<%= link_to 'Edit', edit_propaganda_path(@propaganda) %> |
<% end %>
<%= link_to 'Back', propagandas_path %>