config/routes.rb
Dialeto::Application.routes.draw do
  match 'categorias/auto_complete' => 'categorias#auto_complete'
  match 'perfis/auto_complete' => 'perfis#auto_complete'
  match 'categorias/:id_categoria/propagandas' => 'propagandas#propagandas_da_categoria'
  match 'categorias/:id_categoria/videos' => 'videos#videos_da_categoria'
  match 'videos/validate_video' => 'videos#validate_video'
  
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  
  resources :token_authentications, :only => [:create, :destroy]
  resources :user, :controller => "user"
  resources :users
  resources :contatos
  resources :videos
  resources :propagandas
  resources :categorias
  resources :perfis

  root :to => "perfis#index"
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_reader :categoria_tokens, :perfil_tokens
  attr_accessible :categoria_tokens, :perfil_tokens, :images_attributes, :nome, :media, :tag_list, :descricao, :panda_video_id

  scope :videos_do_usuario, lambda {|user|
    {
      :select => "DISTINCT videos.id, videos.nome, videos.descricao, videos.created_at, videos.updated_at, videos.status, videos.panda_video_id, videos.content_type, videos.file_size, videos.file_name, videos.original_file_name",
      :joins => "LEFT JOIN perfis_videos pv ON pv.video_id = videos.id " +
                "LEFT JOIN perfis p ON pv.perfil_id = p.id " +
                "LEFT JOIN users u ON u.perfil_id = p.id",
      :conditions => ["u.id = ?", user], :group => "videos.id, videos.nome, videos.descricao, videos.created_at, videos.updated_at, videos.status, videos.panda_video_id, videos.content_type, videos.file_size, videos.file_name, videos.original_file_name"
    }
  }

  acts_as_taggable_on :tags
  has_many :images, :as => :owner, :dependent => :destroy
  has_and_belongs_to_many :categorias, :join_table => "categorias_videos"
  has_and_belongs_to_many :perfis, :join_table => "perfis_videos"
  validates_inclusion_of :status, :in => %w[pending completed]
  validates_presence_of :nome, :perfis, :categorias, :images, :panda_video_id
  validates_uniqueness_of :nome, :case_sensitive => false

  accepts_nested_attributes_for :images, :reject_if => lambda { |t| t['image'].nil? }

  STATUS = %w[pending completed]

  def initialize(*params)
    super(*params)

    if (@new_record)
      self.status = 'pending'
    end
  end

  def panda_video
    @panda_video ||= Panda::Video.find(panda_video_id)
  end

  def nome_perfis
    nomes = ""
    perfis.each do |perfil|
      nomes << "#{perfil.nome}, "
    end
    nomes
  end

  def images_url
    images_url = []
    images.each{|image| images_url << image.image_url}
    images_url
  end

  def authenticated_media_url(options={})
    return unless completed?
    check_s3_connection
    options.reverse_merge! :expires_in => 10.minutes, :use_ssl => false
    AWS::S3::S3Object.url_for file_name << content_type, 'dialeto_video', options
  end

  def as_json(options)
    super(:only => [:id, :created_at, :nome, :updated_at, :descricao, :content_type, :file_size, :original_file_name], :methods => [:tag_list, :images_url, :authenticated_media_url], :include => {:categorias => {:only => [:id]}})
  end

  def categoria_tokens=(ids)
    self.categoria_ids = ids.split(",")
  end

  def perfil_tokens=(ids)
    self.perfil_ids = ids.split(",")
  end

  def completed?
    self.status == 'completed'
  end

  private
  def check_s3_connection
    if !AWS::S3::Base.connected?
      yml = YAML.load(File.read("config/s3.yml"))
      AWS::S3::Base.establish_connection!(:access_key_id => yml['access_key_id'], :secret_access_key => yml['secret_access_key'])
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :authenticate_user!, :except => :validate_video
  protect_from_forgery :except => :validate_video
  load_and_authorize_resource
  skip_authorize_resource :only => :validate_video

  def index    
    if can? :manage, Video
      @videos = Video.all
    else
      @videos = Video.videos_do_usuario(current_user).where(:status => 'completed')
    end
    respond_to do |format|
      format.html
      format.json  { render :json => @videos }
    end
  end
  
  def videos_da_categoria
    if(can? :manage, Video)
      categoria = Categoria.find(params[:id_categoria])
    else
      categoria = Categoria.categorias_do_usuario(current_user).where(:id => params[:id_categoria]).first
    end
    raise ActiveRecord::RecordNotFound.new if categoria.nil?
    @videos = categoria.videos.find_all{ |video| video.completed? }
    
    respond_to do |format|
      format.html { render :template => "videos/index.html.erb" }
      format.json  { render :json => @videos }
    end
  end
  
  def validate_video
    params_validated = params['event'] && params['event'] == 'video-encoded' && params['video_id'] && !params['video_id'].blank?
    if params_validated
      video = Video.find_by_panda_video_id(params['video_id'])
      if video
        panda_video = Panda::Video.find(video.panda_video_id)
        encoded_video = panda_video.encodings.first

        video.original_file_name = panda_video.original_filename
        video.content_type = encoded_video.extname
        video.file_size = encoded_video.file_size
        video.file_name = encoded_video.path
        video.status = 'completed'
        
        if video.save!
          render :nothing => true, :status => 200
        else
          render :nothing => true, :status => 500
        end
        return
      end
    end
    render :nothing => true, :status => 200
  end

  def show
    @video = Video.find(params[:id])

    unless can? :manage, Video
      @video = nil unless Video.videos_do_usuario.include? @video
    end
    
    if @video
      @encoded_video = @video.panda_video.encodings.first
      respond_to do |format|
        format.html
        format.json  { render :json => @videos }
      end
    elsif
      render :status => 404
    end
  end

  def new
    @video = Video.new
    @video.images = []
    3.times do
      image = Image.new
      image.owner = @video
      @video.images << image
    end
  end

  def edit
    @video = Video.find(params[:id])
  end

  def create
    @video = Video.new(params[:video])
    
    if @video.save
      redirect_to(@video, :notice => 'Video criado com sucesso.')
    else
      render :action => "new"
    end
  end

  def update
    @video = Video.find(params[:id])
    params[:video].delete(:media) if params[:video][:media].blank?
    
    if @video.update_attributes(params[:video])
      redirect_to(@video, :notice => 'Video atualizado com sucesso.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    
    redirect_to(videos_url)
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<% if @video.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@video.errors.count, "erro") %> proibiram o video de ser salvo.</h2>
    <ul>
	    <% @video.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
    </ul>
  </div>
<% end %>

<%= simple_form_for(@video, :html => {:multipart => true, :id => "insert-form"}) do |f| %>
	<div class="form-left">
		<%= f.label :nome, "Nome" %>
	</div>
	<div class="form-right">
		<%= f.text_field :nome %>
	</div>
	<div class="form-left">
		<%= f.label :descricao, "Descrição" %>
	</div>
	<div class="form-right">
		<%= f.text_area :descricao %>
	</div>
	<div class="form-left">
		<%= f.label :categoria_tokens, "Categorias" %>
	</div>
	<div class="form-right">
		<%= f.text_field :categoria_tokens, "data-pre" => @video.categorias.map(&:attributes).to_json %>
	</div>
	<div class="form-left">
		<%= f.label :perfil_tokens, "Perfis" %>
	</div>
	<div class="form-right">
		<%= f.text_field :perfil_tokens, "data-pre" => @video.perfis.map(&:attributes).to_json %>
	</div>
	<% if @video.new_record? %>
			<div class="form-left">
				<label>Media</label>
			</div>
			<div class="form-right">
				<input type="hidden" name="video[panda_video_id]" id="returned_video_id" />
			  <div id="upload_progress" class="panda_upload_progress"></div>
			</div>
	<% end %>
	<div class="form-left">
		<%= f.label :tags, "Tags" %>
	</div>
	<div class="form-right">
		<%= f.text_field :tag_list, "style" => "width:395px;" %>
		<span class="inline-help">Você deve separar as tags por virgula.</span>
	</div>
	<%= f.fields_for :images do |builder| %>
		<% if @video.new_record? %>
			<div class="form-left">
				<%= builder.label :image, "Imagem" %>
			</div>
			<div class="form-right">
					<%= builder.file_field :image, :class => "txt", :id => "preview" %>
	        <span class="inline-help">A imagem precisa ter 448x250 pixels.</span>
	    </div>
		<% end %>
	<% end %>
  <div class="clear" style="text-align:right; width:372px; padding-top: 30px;">
		<%= f.submit :submit %>
	</div>
<% end %>
<%= content_for :js do %>
<% if @video.new_record? %>
	<% auth_params = Panda.signed_params('post', "/videos.json") %>
	$("#returned_video_id").pandaUploader(<%=raw auth_params.to_json %>, {
	  upload_progress_id: 'upload_progress'
	});
<% end %>
$("#video_categoria_tokens").tokenInput("/categorias/auto_complete.json", {
	crossDomain: false,
	prePopulate: $(this).data("pre"),
  theme: "facebook"
});
$("#video_perfil_tokens").tokenInput("/perfis/auto_complete.json", {
	crossDomain: false,
	prePopulate: $(this).data("pre"),
  theme: "facebook"
});
$("#video_nome").focus();
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h2 class="top-title">Videos</h2>
<div class="videos">
	<div style="margin:10px 0px 20px 10px">
		<%= link_to 'Inserir Novo Video', new_video_path, :id => "add-video", :class => "submit button large ui-corner-all" %>
  </div>
	<table class="list-table">
		<thead class="ui-widget-header ui-corner-all">
			<tr>
				<th width="100%">Nome</th>
				<th colspan="4">Ações</th>
			</tr>
		</thead>
		<tbody>    	
			<% @videos.each do |video| %>
				<tr>
					<td><%= video.nome %></td>
					<td><%= link_to "Visualizar", video, :class => "view-record" %></td>
					<% if can? :manage, @videos %>
						<td><%= link_to "Editar", edit_video_path(video), :class => "edit-record" %></td>
						<td><%= link_to "Deletar", video, :method => :delete, :confirm => "Você tem certeza?", :class => "delete-record" %></td>
					<% end %>
			  </tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/videos/new.html.erb
<h2 class="top-title">Inserir novo Video</h2>

<%= render 'form' %>

<%= link_to 'Back', videos_path, :class => "new" %>

app/views/videos/show.html.erb
<p>
  <b>Nome:</b>
  <%= @video.nome %>
</p>

<p>
  <b>Descricao:</b>
  <%= @video.descricao %>
</p>

<p>
	<b>Categorias:</b>
	<%= @video.categorias.count %>
</p>
<% if @video.completed? %>
  <video id="movie" width="<%= @encoded_video.width %>" height="<%= @encoded_video.height %>" preload="none" 
    poster="<%= @encoded_video.screenshots.first %>" controls>
    <source src="<%= @video.authenticated_media_url %>" type="video/mp4">
  </video>
<% end %>
<p>
	<b>Imagens:</b>
	<% @video.images.each do |builder| %>		
		<p>
			<%= image_tag builder.image_url %>
		</p>
	<% end %>
</p>
<% if can? :manage, @video %>
	<%= link_to 'Edit', edit_video_path(@video) %> |
<% end %>
<%= link_to 'Back', videos_path %>