config/routes.rb
Dialeto::Application.routes.draw do
  match 'categorias/auto_complete' => 'categorias#auto_complete'
  match 'perfis/auto_complete' => 'perfis#auto_complete'
  match 'categorias/:id_categoria/propagandas' => 'propagandas#propagandas_da_categoria'
  match 'categorias/:id_categoria/videos' => 'videos#videos_da_categoria'
  match 'videos/validate_video' => 'videos#validate_video'
  
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  
  resources :token_authentications, :only => [:create, :destroy]
  resources :user, :controller => "user"
  resources :users
  resources :contatos
  resources :videos
  resources :propagandas
  resources :categorias
  resources :perfis

  root :to => "perfis#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login
  usar_como_cpf :cpf
  
  belongs_to :perfil
  
  validates_presence_of :cpf, :telefone, :nome, :nascimento, :endereco, :sexo, :role, :username, :perfil
  validates_inclusion_of :sexo, :in => %w[masculino feminino]
  validates_inclusion_of :role, :in => %w[admin user editor]
  validates_uniqueness_of :username, :case_sensitive => false
  validates_uniqueness_of :email, :case_sensitive => false

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :perfil_id, :role, :username, :login, :endereco, :telefone, :nome, :nascimento, :sexo, :cpf, :nascimento_str, :locked, :perfil

  ROLES = %w[admin user editor]
  SEXO = %w[masculino feminino]
  
  def nascimento_str
    self.nascimento.strftime('%d/%m/%Y') unless nascimento.nil?
  end

  def nascimento_str=(nascimento_str)
    self.nascimento = Date.strptime(nascimento_str, '%d/%m/%Y')
  rescue ArgumentError
    @nascimento_invalid = true
  end
  
  def active_for_authentication?
    !self.locked
  end
  
  protected
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
  end
    
end

app/controllers/user_controller.rb
#encoding: utf-8
class UserController < ApplicationController
  load_and_authorize_resource
  
  def index
    @users = User.all.delete_if {|user| user.id == current_user.id}
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Usuário criado com sucesso."
      redirect_to user_index_path
    else
      render :action => 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update  
    @user = User.find(params[:id])
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?    
    if @user.update_attributes(params[:user])
      flash[:notice] = "Usuário alterado com sucesso."
      redirect_to user_index_path
    else
      render :action => 'edit'
    end
  end
  
end

app/views/user/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "erro") %> proibiram o usuário de ser salvo.</h2>
    <ul>
	    <% @user.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-left">
	<%= f.label :nome %>
</div>
<div class="form-right">
	<%= f.text_field :nome, :class => "txt" %>
</div>
<div class="form-left">
	<%= f.label :email %>
</div>
<div class="form-right">
	<%= f.email_field :email, :require => true, :class => "txt" %>
</div>
<div class="form-left">
	<%= f.label :sexo %>
</div>
<div class="form-right">
	<%= f.collection_select :sexo, User::SEXO, :to_s, :humanize %></p>
</div>
<div class="form-left">
	<%= f.label :nascimento %>
</div>
<div class="form-right">
	<%= f.text_field :nascimento_str %>
</div>
<div class="form-left">
	<%= f.label :cpf %>
</div>
<div class="form-right">
	<%= f.text_field :cpf, :class => "txt" %>	
</div>
<div class="form-left">
	<%= f.label :telefone %>
</div>
<div class="form-right">
	<%= f.text_field :telefone, :class => "txt" %>	
</div>
<div class="form-left">
	<%= f.label :endereco, "Endereço" %>
</div>
<div class="form-right">
	<%= f.text_field :endereco, :class => "txt" %>
</div>
<div class="form-left">
	<%= f.label :username %>
</div>
<div class="form-right">
	<%= f.text_field :username, :class => "txt" %>
</div>
<div class="form-left">
	<%= f.label :password, "Senha" %>
</div>
<div class="form-right">
	<%= f.password_field :password, :class => "txt" %>	
</div>
<div class="form-left">
	<%= f.label :password, "Confirmar" %>
</div>
<div class="form-right">
	<%= f.password_field :password_confirmation, :class => "txt" %>	
</div>
<div class="form-left">
	<%= f.label :perfil %>
</div>
<div class="form-right">
	<%= f.collection_select( :perfil_id, Perfil.order('descricao'), :id, :descricao, {:prompt => false}) %>
</div>
<div class="form-left">
	<%= f.label :role, "Nível de Acesso" %>
</div>
<div class="form-right">
	<%= f.collection_select :role, User::ROLES, :to_s, :humanize, {:include_blank => false} %>
</div>
<div class="form-left">
	<%= f.label :locked, "Desativado" %>
</div>
<div class="form-right">
	<%= f.radio_button(:locked, true) %>Sim
	<%= f.radio_button(:locked, false) %>Não
</div>

<div class="clear" style="text-align:right; width:372px">
  <%= f.submit :submit %>
</div>
<%= content_for :js do %>
$(document).ready(function() {
	$("#user_nascimento_str").mask("99/99/9999");
	$("#user_telefone").mask("(99)9999-9999");
	$('#user_cpf').bind('blur', function(){
		validaCPF(this);
	});
	$("#user_cpf").mask("999.999.999-99");
});
<% end %>

app/views/user/edit.html.erb
<h2 class="top-title">Editar Usuário</h2>

<%= simple_form_for @user, :url => user_path, :html => {:id => "insert-form"} do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

app/views/user/index.html.erb
<h2 class="top-title">Usuários</h2>
<% if can? :manage, @users %>	
	<div class="clear"></div>
	<div style="margin:40px 0px 20px 10px">
		<%= link_to "Inserir Novo Usuário", new_user_path, :class => "submit button large ui-corner-all" %>
	</div>
		<table class="list-table">
			<thead class="ui-widget-header ui-corner-all">
		  	<tr>
      		<th width="220">Nome</th>
          <th width="220">Email</th>
          <th width="100">Status</th>
          <th width="100">Perfil</th>
          <th width="100">Nível</th>
          <th colspan="1">Ações</th>
		    </tr>
		  </thead>
		  <tbody>
				<% @users.each do |user| %>
					<tr>
			   		<td><%= user.nome %></td>
			      <td><%= user.email %></td>
						<% if user.locked %>
			      	<td><span class="button submit medium red-back fixed-width-100 ui-corner-all">Suspenso</span></td>
						<% elsif %>
							<td><span class="button submit medium green-back fixed-width-100 ui-corner-all">Liberado</span></td>
						<% end %>
			      <td><%= user.perfil.descricao %></td>
			      <td><%= user.role.humanize %></td>
			      <td><%= link_to "Editar", edit_user_path(user), :class => "edit-record" %></td>
			    </tr>
				<% end %>
			</tbody>
		</table>
<% else %>
  <p>Não Autorizado</p>
<% end %>

app/views/user/new.html.erb
<h2 class="top-title">Inserir novo usuário</h2>

<%= simple_form_for @user, :url => user_index_path, :html => {:id => "insert-form"}   do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end %>