config/routes.rb
Dialeto::Application.routes.draw do
  match 'categorias/auto_complete' => 'categorias#auto_complete'
  match 'perfis/auto_complete' => 'perfis#auto_complete'
  match 'categorias/:id_categoria/propagandas' => 'propagandas#propagandas_da_categoria'
  match 'categorias/:id_categoria/videos' => 'videos#videos_da_categoria'
  match 'videos/validate_video' => 'videos#validate_video'
  
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  
  resources :token_authentications, :only => [:create, :destroy]
  resources :user, :controller => "user"
  resources :users
  resources :contatos
  resources :videos
  resources :propagandas
  resources :categorias
  resources :perfis

  root :to => "perfis#index"
end

app/helpers/layout_helper.rb
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_logged.html.erb
<div id="container">
	<div id="header">
		<div id="header-top">
			<div id="top-block-left">
				<p>Bem vindo <%= current_user.nome %> [ <%= current_user.role.humanize %> ]</p>
			</div>
			<ul id="top-toolbox">
				<li><%= link_to "Minha Conta", edit_user_registration_path, :id => "profile-link" %></li>
				<li><%= link_to "Logout", destroy_user_session_path, :id => "logout-link" %></li>
			</ul>
			<div class="clear"></div>
		</div>
		<div id="header-middle">
			<%= link_to "LLEDD.TV", root_url, :id => "logo" %>
		</div>
		<div id="menu">
			<ul class="topnav">
				<li><%= link_to("Perfil", {:controller => "perfis"}, :id => "menu-perfil")%></li>
				<li><%= link_to("Categoria", {:controller => "categorias"}, :id => "menu-categorias")%></li>
				<li><%= link_to("Video", {:controller => "videos"}, :id => "menu-videos")%></li>
				<li><%= link_to("Propaganda", {:controller => "propagandas"}, :id => "menu-propaganda")%></li>
        		<li class="right"><%= link_to("Suporte", new_contato_path, :id => "menu-suporte") %></li>
				<% if can? :manage, @users %>
					<li class="right"><%= link_to("Usuários", user_index_path, :id => "menu-usuario") %></li>
				<% end %>
			</ul>
		</div>
	</div>
	<div class="clear"></div>
	<div id="status">
		<% flash.each do |name, msg| %>
		  <%= content_tag :div, msg, :id => "flash_#{name}" %>
		<% end %>
	</div>
	<div id="content">
		<%= yield %>
	</div>
</div>
<div class="clear"></div>
<div id="footer-container">
	<div id="footer">
		<div id="footer-logo">
			<p id="copyright">Copyright &copy; 2011 Powered by lledd.tv</p>
		</div>
		<ul class="menu">
			<li><%= link_to "Usuários", user_index_path %></li>
			<li><%= link_to "Perfil", perfis_path %></li>
			<li><%= link_to "Categorias", categorias_path %></li>
			<li><%= link_to "Vídeos", videos_path %></li>
			<li><%= link_to "Propaganda", propagandas_path %></li>
		</ul>
		<div class="clear"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>LLEDD.TV - Painel de Controle</title>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag 'jquery.uniform.min' %>
    <%= javascript_include_tag 'jquery.maskedinput-1.3.min' %>
    <%= javascript_include_tag 'jquery.tokeninput' %>
    <%= javascript_include_tag 'jquery.panda-uploader.min.js' %>
    <% if content_for? :js_file %>
        <%= yield :js_file %>
    <% end %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
	<% if user_signed_in? %>
  	    <body>
	<% else %>
 		<body id="login-body">
	<% end %>
    <% if user_signed_in? %>
        <%= render :partial => "layouts/logged" %>
    <% else %>
        <div id="login-title">
            <h1>Dialetto</h1>
        </div>
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
        <%= yield %>
    <% end %>
    <script type="text/javascript">
        <%= yield :js %>
    </script>
  </body>
</html>